# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for Weather App Pro (release-plan item 1.2).

Build with (or use build.ps1, which also runs tests and the secret
scan):

    .venv/Scripts/pyinstaller app.spec --noconfirm

Requires build/version_info.txt, generated by
tools/make_release_assets.py.
"""

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("VERSION", "."),
        ("resources", "resources"),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        "PyQtWebEngine",
        "PyQt5.QtWebEngineWidgets",
        "PyQt5.QtWebEngine",
        "test_lottie",
        "tools",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="WeatherAppPro",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon="resources/icons/app.ico",
    version="build/version_info.txt",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="WeatherAppPro",
)
