"""
make_release_assets.py
======================

Generates the two release build assets (release plan items 1.1 and
1.3):

    1. resources/icons/app.ico, a multi-size Windows icon rendered
       from the clear-sky SVG the app already ships
    2. build/version_info.txt, the Windows version resource that makes
       Explorer's file properties show the VERSION file's version

Run from the project root with the project venv:

    .venv/Scripts/python tools/make_release_assets.py

Needs Pillow and PyQt5 (both in requirements-build.txt).
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from PyQt5.QtCore import Qt  # noqa: E402
from PyQt5.QtGui import QGuiApplication, QPainter, QPixmap  # noqa: E402
from PyQt5.QtSvg import QSvgRenderer  # noqa: E402
from PIL import Image  # noqa: E402

import config  # noqa: E402
import paths  # noqa: E402
from managers.icon_manager import IconManager  # noqa: E402

ICON_SIZES = [16, 24, 32, 48, 64, 128, 256]

ICON_TARGET = paths.resources_root() / "icons" / "app.ico"
VERSION_TARGET = PROJECT_ROOT / "build" / "version_info.txt"


def render_icon() -> None:
    """
    Render the clear-sky SVG at every size and pack an .ico.
    """

    # QPixmap needs a GUI application, not just QCoreApplication.
    app = QGuiApplication(sys.argv or ["make_release_assets"])

    renderer = QSvgRenderer(IconManager.get_icon_path(800))

    if not renderer.isValid():
        raise RuntimeError("could not load the clear-sky SVG")

    # Pillow packs the ICO from one large source image, resized down
    # per size entry.
    master_path = Path(app.applicationDirPath()) / "icon_master.png"

    pixmap = QPixmap(256, 256)
    pixmap.fill(Qt.transparent)

    painter = QPainter(pixmap)
    renderer.render(painter)
    painter.end()

    pixmap.save(str(master_path))

    master = Image.open(master_path)

    ICON_TARGET.parent.mkdir(parents=True, exist_ok=True)

    master.save(
        ICON_TARGET,
        format="ICO",
        sizes=[(size, size) for size in ICON_SIZES],
    )

    master_path.unlink()

    print(f"icon written: {ICON_TARGET}")


def render_version_file() -> None:
    """
    Write the PyInstaller version resource from config.APP_VERSION.
    """

    version = config.APP_VERSION.lstrip("v")
    parts = [int(piece) for piece in version.split(".")]

    while len(parts) < 4:
        parts.append(0)

    filevers = tuple(parts[:4])

    VERSION_TARGET.parent.mkdir(parents=True, exist_ok=True)

    VERSION_TARGET.write_text(f"""# UTF-8
#
# Generated by tools/make_release_assets.py from the VERSION file.
# Do not edit by hand.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'Weather App Pro'),
            StringStruct('FileDescription', 'Weather App Pro'),
            StringStruct('FileVersion', '{version}.0'),
            StringStruct('InternalName', 'WeatherAppPro'),
            StringStruct('LegalCopyright', 'MIT License. Copyright (c) 2026 Weather App Pro.'),
            StringStruct('OriginalFilename', 'WeatherAppPro.exe'),
            StringStruct('ProductName', 'Weather App Pro'),
            StringStruct('ProductVersion', '{version}.0'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding="utf-8")

    print(f"version resource written: {VERSION_TARGET}")


if __name__ == "__main__":
    render_icon()
    render_version_file()
